#########################
## Modernizr Configuration
#########################
modernizr:
  classPrefix: ''
  options:
    - setClasses
  'feature-detects':
    - svg/smil
    - inputtypes


#########################
## JavaScript Assets to Include, in order
##
## Use <<modernizr>> to include the custom Modernizr build from above
#########################
js:
  app:
    - <<modernizr>>
    - bower_components/prism/prism.js
    - bower_components/prism/components/prism-css.js
    - bower_components/prism/components/prism-css-extras.js
    - bower_components/prism/components/prism-scss.js
    - bower_components/prism/components/prism-bash.js
    - bower_components/prism/components/prism-markup.js
    - bower_components/prism/components/prism-javascript.js
    - library/js/prism-activate.js
